language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - cd sdnsite
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runserver
