language: python
python:
  - "2.7"
  - "3.5"

env:
  DJANGO=1.10
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO --use-mirrors
# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runserver
