# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posting',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(default='make an app', max_length=50)),
                ('description', models.CharField(default='a decent job', max_length=1000)),
                ('status', models.IntegerField(default=0)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
