# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_posting_total_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='company_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='posting',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='posting',
            name='post_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
