# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170424_1830'),
        ('posting', '0004_auto_20170410_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag')),
            ],
        ),
    ]
