# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170424_1830'),
        ('posting', '0005_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
