# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-26 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_posting_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='posting',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
