# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20170425_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
