# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('deliverable', models.CharField(max_length=1000)),
                ('total_pay', models.FloatField()),
                ('percent_up_front', models.FloatField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('file_reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('biography', models.CharField(max_length=300)),
                ('business', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('skill_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='posting',
            name='posting_text',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='posting',
            name='contractor_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='description',
            field=models.CharField(default='a decent job', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posting',
            name='job_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='job_title',
            field=models.CharField(default='make an app', max_length=50),
        ),
        migrations.AddField(
            model_name='posting',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posting',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Posting'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Member'),
        ),
        migrations.AddField(
            model_name='member_tag',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag'),
        ),
        migrations.AddField(
            model_name='job_tag',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Posting'),
        ),
        migrations.AddField(
            model_name='job_tag',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Member'),
        ),
        migrations.AddField(
            model_name='file',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Member'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Member'),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Posting'),
        ),
    ]
