# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170330_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='employer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Member'),
        ),
    ]
