# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='id',
        ),
        migrations.AlterField(
            model_name='posting',
            name='employer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Member'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
