# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-06 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170330_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='skill_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
