# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-10 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170406_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
