# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170410_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_tag',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting'),
        ),
        migrations.AlterField(
            model_name='member_tag',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
