# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cover_letter', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('deliverable', models.CharField(max_length=1000)),
                ('total_pay', models.FloatField()),
                ('percent_up_front', models.FloatField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('file_reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('biography', models.CharField(max_length=300)),
                ('business', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=0)),
                ('job_title', models.CharField(default='make an app', max_length=50)),
                ('description', models.CharField(default='a decent job', max_length=1000)),
                ('status', models.IntegerField(default=0)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Posting')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('skill_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member_tag',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tag'),
        ),
        migrations.AddField(
            model_name='job_tag',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Posting'),
        ),
        migrations.AddField(
            model_name='job_tag',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='file',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Posting'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Posting'),
        ),
        migrations.AddField(
            model_name='application',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.File'),
        ),
    ]
