# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractor_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='job_tag',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='job_tag',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='member_tag',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='member_tag',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer_id',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Job_Tag',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Member_Tag',
        ),
        migrations.DeleteModel(
            name='Posting',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
