# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-26 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
